export const httpCodes = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502
};

export const errorSource = {
  CLIENT_ERROR: 'CLIENT_ERROR',
  FIRESTORE_ERROR: 'FIRESTORE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};